src/models/blog.py
from src.extensions import db
from src.models.user import User


class Category(db.Document):
    category_name = db.StringField(default="")

    meta = {
        "auto_create_index": True,
        "index_background": True
    }


class Blog(db.Document):
    category_id = db.ObjectIdField(Category)
    blog_user_id = db.ObjectIdField(User)
    blog_text = db.StringField(default="")
    blog_creation_date = db.DateTimeField()
    blog_read_count = db.IntField(default=0)
    blog_rating_count = db.IntField(default=0)

    meta = {
        "auto_create_index": True,
        "index_background": True,
        "indexes": ["category_id", "blog_user_id"]
    }


class Comment(db.Document):
    blog_id = db.ObjectIdField(Blog)
    blog_comment = db.StringField(default="")
    comment_user_id = db.ObjectIdField(User)
    blog_rating = db.IntField()
    blog_comment_date = db.DateTimeField()

    meta = {
        "auto_create_index": True,
        "index_background": True,
        "indexes": ["blog_id"]
    }

src/models/user.py
from flask_user import UserMixin
from src.extensions import db


class User(db.Document, UserMixin):
    
    # Active set to True to allow login of user
    name = "User"
    active = db.BooleanField(default=True)
    
    # User authentication information
    username = db.StringField(default="")
    password = db.StringField()
    
    # User Information
    first_name = db.StringField(default="")
    last_name = db.StringField(default="")
    
    email = db.StringField(default="")
    email_confirmed_at = db.DateTimeField()
    
    # Relationships  (Roles: user or user and Admin)
    roles = db.ListField(db.StringField(), default=["user"])

    meta = {
        "auto_create_index": True,
        "index_background": True,
        "indexes": ["email"],
    }

src/routes/blogs/__init__.py
from flask import Blueprint

bp = Blueprint('blogs', __name__)

from src.routes.blogs import routes

src/routes/blogs/routes.py
import json
import datetime
from flask_user import (
    login_required,
    current_user
)
from flask import (
    render_template,
    redirect,
    url_for,
    request
)
from src.models.user import User
from src.models.blog import Blog, Category, Comment
from src.routes.blogs import bp


# Global variable
global_all_category_num = []
global_all_category_name = []


def get_all_categories():
    global global_all_category_num, global_all_category_name

    for cat in Category.objects.all():
        dict_cat = json.loads(cat.to_json())
        global_all_category_num.append(dict_cat['_id']['$oid'])
        global_all_category_name.append(dict_cat['category_name'])


@bp.route("/blogs")
def blogs():
    return redirect(url_for('blogs.list_all_blogs'))


# CRUD for Blogs
@bp.route("/listAllBlogs")
def list_all_blogs():
    all_blogs = reversed(Blog.objects.all())  # reverse to display recent ones on the top
    all_users = User.objects.all()
    all_categories = Category.objects.all()
    return render_template('blogs/list_all_blogs.html', all_blogs=all_blogs, all_users=all_users, all_categories=all_categories)


@bp.route("/createBlog", methods=['GET', 'POST'])
@login_required
def create_blog():
    if request.method == 'POST':
        category_id = request.form.get("category_id")
        blog_text = request.form.get("blog_text")
        today = datetime.datetime.utcnow()
        blog_user_id = current_user.id
        blog_read_count = 0
        blog_rating_count = 0

        newBlog = Blog(category_id=category_id,
                       blog_user_id=blog_user_id,
                       blog_text=blog_text,
                       blog_creation_date=today,
                       blog_read_count=blog_read_count,
                       blog_rating_count=blog_rating_count)

        newBlog.save()
        return redirect("blogs")
    else:
        return render_template("blogs/create_blog.html", all_category_id=global_all_category_num, all_category_name=global_all_category_name)


@bp.route("/viewBlog")
@login_required
def view_blogs():
    all_categories = Category.objects.all()
    
    user = User.objects.filter(id=current_user.id).all()[0]
    if user.username == 'admin':
        all_self_blogs = Blog.objects.all()
    else:
        all_self_blogs = Blog.objects.filter(blog_user_id=current_user.id).all()

    all_self_blogs = reversed(all_self_blogs)  # reverse to display recent ones on the top
    return render_template("blogs/view_blog.html", all_self_blogs=all_self_blogs, all_categories=all_categories)


@bp.route("/self_blog_detail/<string:blog_id>/<string:blog_category>", methods=["GET", "POST"])
@login_required
def self_blog_detail(blog_id, blog_category):
    blog = Blog.objects.filter(id=blog_id).first()
    if request.method == "POST":
        if request.form['action'] == 'Update':
            blog.blog_text = request.form.get('blog_text')
        elif request.form['action'] == 'Delete':
            Blog.objects.filter(id=blog_id).first().delete()
        blog.save()
        return redirect('/viewBlog')
    return render_template("blogs/self_blog_detail.html", blog_text=blog.blog_text)


@bp.route('/blogDetail/<string:blog_id>/<string:username>/<string:blog_category>', methods=["GET", "POST"])
@login_required
def blog_detail(blog_id, username, blog_category):
    blog = Blog.objects.filter(id=blog_id).first()
    if request.method == 'GET':
        if current_user.id != blog.blog_user_id:
            blog.blog_read_count += 1
            blog.save()

        blog_rating = None
        avg_ratings = list(Comment.objects.aggregate([{'$group': {'_id': '$blog_id', 'avgRating': {'$avg': '$blog_rating'}}}]))
        for rating in avg_ratings:
            if str(list(rating.values())[0]) == blog_id:
                blog_rating = list(rating.values())[1]
        return render_template('blogs/blog_detail.html', blog=blog, rating=blog_rating, author=username, category=blog_category)
    else:
        rate = request.form.get('rating')
        comment = request.form.get('comment')
        blog_id = request.form.get('blog_id')

        old_comment = Comment.objects.filter(blog_id=blog_id).filter(comment_user_id=current_user.id).first()
        today = datetime.datetime.utcnow()

        if old_comment is None:
            blog.blog_rating_count += 1
            blog.save()

            new_comment = Comment(
                blog_id=blog_id,
                comment_user_id=current_user.id,
                blog_comment=comment,
                blog_rating=rate,
                blog_comment_date=today)
            new_comment.save()
        else:
            old_comment.blog_comment = comment
            old_comment.blog_rating = rate
            old_comment.save()
        return redirect('/blogs')

src/routes/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from src.routes.main import routes

src/routes/main/routes.py
import datetime
from flask import redirect, url_for, flash, current_app
from flask_user import UserManager
from src.routes.main import bp
from src.extensions import db
from src.models.user import User


user_manager = UserManager(current_app, db, User)


def password_hashing(password):
    return user_manager.hash_password(password)


@bp.route("/")
@bp.route("/index")
@bp.route("/index.htm")
@bp.route("/index.html")
def home_page():
    """
    Landing/Home Page, accessible before sign in/login. If logged in, user is redirected to the Main Page.
    At first access/touch the user 'admin' is created using environment variables for the password and email address.
    The admin user creation is here as it will be created twice on Heroku if placed in the main code.
    """

    # Create admin user as first/default user, if admin does not exist.
    # Password and e-mail are set using environment variables.
    all_users = [all_user.username for all_user in User.objects.all()]

    if 'admin' not in all_users:
        try:
            user = User(
                username="admin",
                first_name="Administrator",
                last_name="Administrator",
                email='ad@min.com',
                email_confirmed_at=datetime.datetime.utcnow(),
                password=password_hashing('admin'),
            )
            user.roles.append("Admin")
            user.save()

            flash("'admin' account created.", "success")
            bp.logger.info(
                "'admin' account is created at startup if the user doesn't exist: [SUCCESS] - (index.html)."
            )
        except Exception:
            flash("'admin' account not created.", "danger")
            bp.logger.critical(
                "'admin' account is created at startup if the user doesn't exist: [FAILURE] - (index.html)."
            )
    return redirect(url_for('blogs.list_all_blogs'))

src/templates/base.html
{% extends "layout.html" %}

{% block header %}
    <center>
    <nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('blogs.blogs') }}">
          <img src="{{ url_for('static', filename='images/blogverse.png') }}" alt="" width="30" height="30" class="d-inline-block">
          BlogVerse
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-2">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('blogs.blogs') }}">Home</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-2">
            {% if call_or_get(current_user.is_authenticated) %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.edit_user_profile') }}">{{ current_user.username | capitalize or current_user.email | capitalize }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.logout') }}">Sign out</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('blogs.create_blog') }}">Create Blog</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('blogs.view_blogs') }}">My Blogs</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('user.login') }}">Sign in</a>
              </li>
            {% endif %}
          </ul>

        </div>
      </div>
    </nav>
    </center>
{% endblock %}

<div class="content">
    {% block content %}
    {% endblock %}
</div>

{% block footer %}
<center>
<footer class="footer fixed-footer">
    <div>
        <section>
            <a class="footer__item" href="https://linkedin.com/in/abhijitpaul0212">|| LinkedIn </a>
            <a class="footer__item" href="https://github.com/abhijitpaul0212">|| Github </a>
            <a class="footer__item" href="https://medium.com/@abhijit-paul">|| Medium  ||</a>
        </section>
    </div>
    <section class="text-center fixed-footer">
      <div><b><a href="https://github.com/abhijitpaul0212/BlogVerse">{{ user_manager.USER_APP_NAME }} {{ user_manager.USER_APP_VERSION }}</a></b></div>
      <div>&copy; {{ user_manager.USER_COPYRIGHT_YEAR }} {{ user_manager.USER_CORPORATION_NAME }}</div>
    </section>
</footer>

</center>
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} The Home Page of MyBlogs {% endblock %}</h1></span>
{% endblock %} 

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BlogVerse{% block extra_title %}{% endblock %}</title>
        <link rel="stylesheet" href="../static/css/styles.css"/>

        <!-- Bootstrap 5 -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Noto+Sans&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/62998f70b3.js" crossorigin="anonymous"></script>
        
        {% block extra_css %}{% endblock %}
    </head>
    <body class="d-flex flex-column min-vh-100">
        <div class="layout_bg">
            {% block header %}
            {% endblock %}

            <main>
                {# One-time system messages called Flash messages #}
                {% block flash_messages %}
                    {%- with messages = get_flashed_messages(with_categories=true) -%}
                        {% if messages %}
                            {% for category, message in messages %}
                                {% if category=='error' %}
                                    {% set category='danger' %}
                                {% endif %}
                                <div class="alert alert-{{category}}">{{ message|safe }}</div>
                            {% endfor %}
                        {% endif %}
                    {%- endwith %}
                {% endblock %}         

                <div class="content">
                    {% block content %}
                    
                    {% endblock %}
                </div>
            </main>
            <br>
            <br>
            
            {% block footer %}
            {% endblock %}
        </div>


        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

        <!-- Message Chip Timeout -->
        <script src="{{ url_for('static', filename = 'scripts/message.js') }}"></script>

        {# *** Allow sub-templates to insert extra html to the bottom of the body *** #}
        {% block extra_js %}{% endblock %}

    </body>
</html>

src/templates/oops.html
{% extends "layout.html" %}

{% block extra_title %} - Oops!{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12 offset-m1 m10 offset-l1 l10">
            <div class="card center">
                <div class="card-image">
                    <a href="{{ url_for('blogs')}}" class="halfway-fab btn-floating pink pink-darken-1 pulse"><p>[ Home ]</p>
                    </a>
                </div>
                <div class="card-content">
                    <span class="card-title pink-text text-darken-1">{{error_type}}</span>
                    <p>{{excuse}}</p>
                    <p>&nbsp;</p>
                    <p>BlogVerse Message - {{error}}</p>
                </div>
                <div class="card-action">
                    <a href="{{ url_for('user.logout') }}">[ Sign Out ]</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}